export const MOCK_MACHINES = [
  {
    id: '1',
    category: 'Tractor',
    subCategory: '4WD',
    brand: 'Mahindra',
    model: '575 DI',
    year: '2022',
    serialNo: '1234',
    condition: 'Good',
    sellingReason: 'Upgrading',
    usageLevel: 'medium',
    isNegotiable: true,
    hasRepair: false,
    repairDetails: '',
    availability: { key: 'immediately' },
    ownershipConfirmed: true,
    askingPrice: '450000',
    media: [
      {
        uri: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDnWzOzGWPfeLaPQJln5vOU_MHtTO0nNV-5hBSYeXPjfDqK_ca-wIApdRIfyaeKIJRSaLDDltixctVaFbsc2OHSO7Uuc23rxilZJ2RE4A-ONJpiaPyGKba_jCRl4CGSynzUfc0lGhpwCp672LZU10IauVkY0A3F6I5Z0fW4X6wSOEQKIw9hxVX8P9NsCzKiOGIfum_EBU0yT1xc1bTf9AWHmAnnXLde1huSydll1UF_MRVMhsQE2R5vADGHwMk9rtFENRbNuvunTl0Z',
        type: 'image',
      },
      {
        uri: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDnWzOzGWPfeLaPQJln5vOU_MHtTO0nNV-5hBSYeXPjfDqK_ca-wIApdRIfyaeKIJRSaLDDltixctVaFbsc2OHSO7Uuc23rxilZJ2RE4A-ONJpiaPyGKba_jCRl4CGSynzUfc0lGhpwCp672LZU10IauVkY0A3F6I5Z0fW4X6wSOEQKIw9hxVX8P9NsCzKiOGIfum_EBU0yT1xc1bTf9AWHmAnnXLde1huSydll1UF_MRVMhsQE2R5vADGHwMk9rtFENRbNuvunTl0Z',
        type: 'image',
      },
    ],
    // Inventory view specific
    expiry: '12 Oct 2024',
    status: 'Live',
    visible: true,
    expired: false,
  },
  {
    id: '2',
    category: 'Tractor',
    subCategory: 'Utility',
    brand: 'John Deere',
    model: '5050D',
    year: '2021',
    serialNo: '5678',
    condition: 'Fair',
    sellingReason: 'Not using',
    usageLevel: 'heavy',
    isNegotiable: false,
    hasRepair: true,
    repairDetails: 'Engine minor work needed',
    availability: { key: 'select_date', value: new Date() },
    ownershipConfirmed: true,
    askingPrice: '620000',
    media: [
      {
        uri: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAhF7qIW6NtKz-J81X-081KzDI0CF3tQfvPbRQ1bCV9MGgUGbRMUjHCRqn-ATkb3GXfAWtxabxtBlLURwFEOaDkHDYZum8Hc7MkCCZlFv9A5Bwl1bmaN5vCEXVw1S09NfpJ3nG8DE9aDhhv5xb5aI1kFG1D6IYOQWr_y3c8hu8JQSVbLpUpaBcZePEkUPpJKkstAn24bItBZr8kmBB0Sp9uCduMEIxPYYVqkJGCv_U-QlNKc3ZJKwl77TrQI7snINFZuPTamjOyShjo',
        type: 'image',
      },
      {
        uri: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAhF7qIW6NtKz-J81X-081KzDI0CF3tQfvPbRQ1bCV9MGgUGbRMUjHCRqn-ATkb3GXfAWtxabxtBlLURwFEOaDkHDYZum8Hc7MkCCZlFv9A5Bwl1bmaN5vCEXVw1S09NfpJ3nG8DE9aDhhv5xb5aI1kFG1D6IYOQWr_y3c8hu8JQSVbLpUpaBcZePEkUPpJKkstAn24bItBZr8kmBB0Sp9uCduMEIxPYYVqkJGCv_U-QlNKc3ZJKwl77TrQI7snINFZuPTamjOyShjo',
        type: 'image',
      },
    ],
    expiry: '01 Sep 2023',
    status: 'Expired',
    visible: false,
    expired: true,
  },
  {
    id: '3',
    category: 'Tractor',
    subCategory: 'Row Crop',
    brand: 'Sonalika',
    model: 'Tiger GT',
    year: '2023',
    serialNo: '9012',
    condition: 'Excellent',
    sellingReason: 'Need cash',
    usageLevel: 'light',
    isNegotiable: true,
    hasRepair: false,
    repairDetails: '',
    availability: { key: 'immediately' },
    ownershipConfirmed: true,
    askingPrice: '215000',
    media: [
      {
        uri: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCKRWIVwkobcjABuxtyeEP8vnjWsiMc-6HOAMqW6MOU7nVZoqEpnrX9h_KwbOuiLy5b9RgeJf_Xvd3OxwPmAwmFK0R2giV22LJtvmUnKYTvUTR4nHrP17v3-TczMdRB5yfVlPDJzbvoeRM3un2RkJGUNskKv8psghP6LFL3kiRxCVQ65lSwpE-xguOUz0PL0uAOP9ERThtdopwSZsl2wnkpbq2xf9s9zUBcxEXhD_Si3nG56joj-vDvlDzWnNLJGL-V5emHrSstFHU1',
        type: 'image',
      },
      {
        uri: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCKRWIVwkobcjABuxtyeEP8vnjWsiMc-6HOAMqW6MOU7nVZoqEpnrX9h_KwbOuiLy5b9RgeJf_Xvd3OxwPmAwmFK0R2giV22LJtvmUnKYTvUTR4nHrP17v3-TczMdRB5yfVlPDJzbvoeRM3un2RkJGUNskKv8psghP6LFL3kiRxCVQ65lSwpE-xguOUz0PL0uAOP9ERThtdopwSZsl2wnkpbq2xf9s9zUBcxEXhD_Si3nG56joj-vDvlDzWnNLJGL-V5emHrSstFHU1',
        type: 'image',
      },
    ],
    expiry: '20 Dec 2024',
    status: 'Live',
    visible: true,
    expired: false,
  },
];
