export const ROUTES = {
  AUTH: {
    LANGUAGE: '/(auth)/language',
    LOGIN: '/(auth)/login',
    OTP: '/(auth)/otp',
    ROLE_SELECT: '/(auth)/role-select',
  },
  FARMER: {
    DASHBOARD: '/(farmer)/dashboard',
    PROFILE_SETUP: '/(farmer)/profile/setup',
    PROFILE_EDIT: '/(farmer)/profile/edit',
    SELL_ADD_DETAILS: '/(farmer)/sell-machine/add-details',
    SELL_UPLOAD_PHOTOS: '/(farmer)/sell-machine/upload-photos',
    SELL_PUBLISH: '/(farmer)/sell-machine/publish',
    SELL_STATUS: '/(farmer)/sell-machine/listing-status',
    BUY_LIST: '/(farmer)/buy-machine/list',
    BUY_FILTERS: '/(farmer)/buy-machine/filters',
    BUY_DETAILS: '/(farmer)/buy-machine/details',
    BUY_UNLOCK_CONTACT: '/(farmer)/buy-machine/unlock-contact',
    RENT_OUT_ADD: '/(farmer)/rent-out/add-machine',
    RENT_OUT_PRICING: '/(farmer)/rent-out/pricing',
    RENT_OUT_AVAILABILITY: '/(farmer)/rent-out/availability',
    RENT_OUT_REQUESTS: '/(farmer)/rent-out/requests',
    RENT_IN_LIST: '/(farmer)/rent-in/list',
    RENT_IN_FILTERS: '/(farmer)/rent-in/filters',
    RENT_IN_DETAILS: '/(farmer)/rent-in/details',
    LABOUR_LIST: '/(farmer)/labour/list',
    LABOUR_PROFILE: '/(farmer)/labour/profile',
    TRANSPORT_SEARCH: '/(farmer)/transport/search',
    TRANSPORT_LIST: '/(farmer)/transport/list',
    TRANSPORT_DETAILS: '/(farmer)/transport/details',
  },
  LABOUR: {
    DASHBOARD: '/(labour)/dashboard',
    PROFILE: '/(labour)/profile',
  },
  TRANSPORTER: {
    DASHBOARD: '/(transporter)/dashboard',
    PROFILE: '/(transporter)/profile',
  },
};
