export const LABOURERS = [
    {
        id: '1',
        name: 'Rajesh Kumar',
        rating: 4.9,
        reviews: 24,
        role: 'Harvesting',
        location: 'Rampur',
        distance: '5km',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAdtbS_uvvRIPfkAPYsl7xYrbH0IpXVSbUO1I3BktIYTSKAh8fz-F71mFhwlwZXT9Y9ERSEcwbcYL-clZYBVAOAD2fOSIIAeHbdDJ3f_13eQ_t3vhp20lk27OB3-CJ_XueC0W5Kv6FLpUWP_pbfRL6UzX4htFygc6hiG9nyVySPasYaofS7wcikpdkIBbgWjBfytu6MT96DND1onCXYVh9bJ0L_bD70WzcmtMUzE2KKABsmG19F93cZlDUWdY8OvPltgZIdU4j2KULg',
        tags: ['Day Shift'],
        verified: true,
        experience: 'Experienced',
        expertise: ['Harvesting', 'Sowing', 'Tractor Driving', 'Fertilizer Spraying', 'Loading'],
        availability: 'Day Shift',
        preferredHours: '6:00 AM to 4:00 PM',
        price: 500
    },
    {
        id: '2',
        name: 'Amit Singh',
        rating: 4.5,
        reviews: 12,
        role: 'Tractor Driver',
        location: 'Rampur',
        distance: '5km',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuApk84aWbcNLQBrZThLO99rZMJAhkWYYqTL4pr5wXSvyE93YkQmg5H-Ibji2CLdU3Y6slnWMLI4qIKI0aJM5nw-vbrEfjcu7DISWgsjyZ3RTJuCDVH3XgQxzaUpK5Ic_OIMg7zagsXedrfEJgUvfFoVKU1Qkjkfo7gXpJzAB1_UymIsYIwbE_2sgs6Hqx6KaiAL3FUPVoU_jrM8_fRNTna0Vu9lVT9vRq-VloZckNSl9mzGdU21JLjSopr13OSIGdimmAVBSHnnfol3',
        tags: ['Night Shift'],
        verified: false,
        experience: 'Intermediate',
        expertise: ['Tractor Driving'],
        availability: 'Night Shift',
        preferredHours: '6:00 PM to 2:00 AM',
        price: 700
    },
    {
        id: '3',
        name: 'Sunita Devi',
        rating: 4.8,
        reviews: 30,
        role: 'Sowing & Weeding',
        location: 'Rampur',
        distance: '5km',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBMy19G-xnQHR98-uu3X-fJmN4JeIyerRi8Jo0Un-8tEy6dD8hEy9F1oTiZjhqttP2gyEXbMAnXUMt9Pz_1UIOENrz_iIJ-AWX2Te1MBmDNTX-xyO5SVeApXokp-vR9NkgPhTATf9NBcXPJGgIW_AQNESTRQ3ANvDt7VSKojeUm7xjDFBZ1VNKQTsir97jOjB4SlTBicV-ynxfAPrpn6XSlJQAhrqqQcw6O2QYZaMVypVOOhTfqfwmiBbOa9Ns2pcR4mhJnJXC-sz01',
        tags: ['Both Shifts'],
        verified: true,
        experience: 'Experienced',
        expertise: ['Sowing', 'Weeding'],
        availability: 'Both Shifts',
        preferredHours: 'Flexible',
        price: 400
    },
    {
        id: '4',
        name: 'Vikram Singh',
        rating: 4.2,
        reviews: 5,
        role: 'Threshing',
        location: 'Rampur',
        distance: '5km',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAbfbohGeqsrCVcBkGcOS0qQ7-CPmcpW537fUQtha8JSYREncudAUn4ICKVhpalq7LsNTchNqD1boGugDxP8IGMTIL_Ro-fg0A_Y0eeovNaFTA_LdYqoN0IpsfttGs1ZRKsfbqvhtdrZJ5wNgADLJC-Yy4nljKfuU-c7-9SzUOK7u8GX1VE4Qb1t9VXTPJhzv6cyLde0DhqnCT6Ew_AoyaWjCu8q-o4EPW2bv0adhAZ8oTFUmcJyWiiDL0ep3-8-Sw4OH3iTsOzJ2iv',
        tags: ['Day Shift'],
        verified: false,
        experience: 'New',
        expertise: ['Threshing'],
        availability: 'Day Shift',
        preferredHours: '9:00 AM to 5:00 PM',
        price: 450,
        busy: true
    }
];
